
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.example.contract.doubleit;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-04-28T22:22:01.186-04:00
 * Generated source version: 3.1.10
 * 
 */

@javax.jws.WebService(
                      serviceName = "DoubleItService",
                      portName = "DoubleItPort",
                      targetNamespace = "http://www.example.org/contract/DoubleIt",
                      wsdlLocation = "classpath:DoubleIt.wsdl",
                      endpointInterface = "org.example.contract.doubleit.DoubleItPortType")
                      
public class DoubleItPortImpl implements DoubleItPortType {

    private static final Logger LOG = Logger.getLogger(DoubleItPortImpl.class.getName());

    /* (non-Javadoc)
     * @see org.example.contract.doubleit.DoubleItPortType#doubleIt(int numberToDouble)*
     */
    public int doubleIt(int numberToDouble) { 
        LOG.info("Executing operation doubleIt");
        System.out.println(numberToDouble);
        try {
            int _return = 24;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
