
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ebay.apis.eblbasecomponents;

import java.util.List;
import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-06-13T12:18:40.273-04:00
 * Generated source version: 2.6.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "Shopping",
                      portName = "Shopping",
                      targetNamespace = "urn:ebay:apis:eBLBaseComponents",
                      wsdlLocation = "ShoppingService.wsdl",
                      endpointInterface = "ebay.apis.eblbasecomponents.ShoppingInterface")
                      
public class ShoppingInterfaceImpl implements ShoppingInterface {

    private static final Logger LOG = Logger.getLogger(ShoppingInterfaceImpl.class.getName());

    /* (non-Javadoc)
     * @see ebay.apis.eblbasecomponents.ShoppingInterface#findReviewsAndGuides(ebay.apis.eblbasecomponents.FindReviewsAndGuidesRequestType  findReviewsAndGuidesRequest )*
     */
    public ebay.apis.eblbasecomponents.FindReviewsAndGuidesResponseType findReviewsAndGuides(FindReviewsAndGuidesRequestType findReviewsAndGuidesRequest) { 
        LOG.info("Executing operation findReviewsAndGuides");
        System.out.println(findReviewsAndGuidesRequest);
        try {
            ebay.apis.eblbasecomponents.FindReviewsAndGuidesResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ebay.apis.eblbasecomponents.ShoppingInterface#findHalfProducts(ebay.apis.eblbasecomponents.FindHalfProductsRequestType  findHalfProductsRequest )*
     */
    public ebay.apis.eblbasecomponents.FindHalfProductsResponseType findHalfProducts(FindHalfProductsRequestType findHalfProductsRequest) { 
        LOG.info("Executing operation findHalfProducts");
        System.out.println(findHalfProductsRequest);
        try {
            ebay.apis.eblbasecomponents.FindHalfProductsResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ebay.apis.eblbasecomponents.ShoppingInterface#getShippingCosts(ebay.apis.eblbasecomponents.GetShippingCostsRequestType  getShippingCostsRequest )*
     */
    public ebay.apis.eblbasecomponents.GetShippingCostsResponseType getShippingCosts(GetShippingCostsRequestType getShippingCostsRequest) { 
        LOG.info("Executing operation getShippingCosts");
        System.out.println(getShippingCostsRequest);
        try {
            ebay.apis.eblbasecomponents.GetShippingCostsResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ebay.apis.eblbasecomponents.ShoppingInterface#getSingleItem(ebay.apis.eblbasecomponents.GetSingleItemRequestType  getSingleItemRequest )*
     */
    public ebay.apis.eblbasecomponents.GetSingleItemResponseType getSingleItem(GetSingleItemRequestType getSingleItemRequest) { 
        LOG.info("Executing operation getSingleItem");
        System.out.println(getSingleItemRequest);
        try {
            ebay.apis.eblbasecomponents.GetSingleItemResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ebay.apis.eblbasecomponents.ShoppingInterface#getCategoryInfo(ebay.apis.eblbasecomponents.GetCategoryInfoRequestType  getCategoryInfoRequest )*
     */
    public ebay.apis.eblbasecomponents.GetCategoryInfoResponseType getCategoryInfo(GetCategoryInfoRequestType getCategoryInfoRequest) { 
        LOG.info("Executing operation getCategoryInfo");
        System.out.println(getCategoryInfoRequest);
        try {
            ebay.apis.eblbasecomponents.GetCategoryInfoResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ebay.apis.eblbasecomponents.ShoppingInterface#geteBayTime(ebay.apis.eblbasecomponents.GeteBayTimeRequestType  geteBayTimeRequest )*
     */
    public ebay.apis.eblbasecomponents.GeteBayTimeResponseType geteBayTime(GeteBayTimeRequestType geteBayTimeRequest) { 
        LOG.info("Executing operation geteBayTime");
        System.out.println(geteBayTimeRequest);
        try {
            ebay.apis.eblbasecomponents.GeteBayTimeResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ebay.apis.eblbasecomponents.ShoppingInterface#getMultipleItems(ebay.apis.eblbasecomponents.GetMultipleItemsRequestType  getMultipleItemsRequest )*
     */
    public ebay.apis.eblbasecomponents.GetMultipleItemsResponseType getMultipleItems(GetMultipleItemsRequestType getMultipleItemsRequest) { 
        LOG.info("Executing operation getMultipleItems");
        System.out.println(getMultipleItemsRequest);
        try {
            ebay.apis.eblbasecomponents.GetMultipleItemsResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ebay.apis.eblbasecomponents.ShoppingInterface#findPopularItems(ebay.apis.eblbasecomponents.FindPopularItemsRequestType  findPopularItemsRequest )*
     */
/*
    public ebay.apis.eblbasecomponents.FindPopularItemsResponseType findPopularItems(FindPopularItemsRequestType findPopularItemsRequest) { 
        LOG.info("Executing operation findPopularItems");
        System.out.println(findPopularItemsRequest);
        try {
            ebay.apis.eblbasecomponents.FindPopularItemsResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }
*/
    public ebay.apis.eblbasecomponents.FindPopularItemsResponseType findPopularItems(
         FindPopularItemsRequestType findPopularItemsRequest) { 
         LOG.info("Executing operation findPopularItems");
         try {
             FindPopularItemsResponseType _return = new FindPopularItemsResponseType();
             SimpleItemArrayType siat = new SimpleItemArrayType();
             List<SimpleItemType> lsit = siat.getItem();
             SimpleItemType sit = new SimpleItemType();
             sit.setPrimaryCategoryName("widgets");
             sit.setItemID("wid-1234");
             sit.setViewItemURLForNaturalSearch("http://www.ebay.com/wid-1234");
             lsit.add(sit);
             _return.setItemArray(siat);
             return _return;
         } catch (Exception ex) {
             ex.printStackTrace();
             throw new RuntimeException(ex);
         }
    }


    /* (non-Javadoc)
     * @see ebay.apis.eblbasecomponents.ShoppingInterface#getItemStatus(ebay.apis.eblbasecomponents.GetItemStatusRequestType  getItemStatusRequest )*
     */
    public ebay.apis.eblbasecomponents.GetItemStatusResponseType getItemStatus(GetItemStatusRequestType getItemStatusRequest) { 
        LOG.info("Executing operation getItemStatus");
        System.out.println(getItemStatusRequest);
        try {
            ebay.apis.eblbasecomponents.GetItemStatusResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ebay.apis.eblbasecomponents.ShoppingInterface#findPopularSearches(ebay.apis.eblbasecomponents.FindPopularSearchesRequestType  findPopularSearchesRequest )*
     */
    public ebay.apis.eblbasecomponents.FindPopularSearchesResponseType findPopularSearches(FindPopularSearchesRequestType findPopularSearchesRequest) { 
        LOG.info("Executing operation findPopularSearches");
        System.out.println(findPopularSearchesRequest);
        try {
            ebay.apis.eblbasecomponents.FindPopularSearchesResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ebay.apis.eblbasecomponents.ShoppingInterface#getUserProfile(ebay.apis.eblbasecomponents.GetUserProfileRequestType  getUserProfileRequest )*
     */
    public ebay.apis.eblbasecomponents.GetUserProfileResponseType getUserProfile(GetUserProfileRequestType getUserProfileRequest) { 
        LOG.info("Executing operation getUserProfile");
        System.out.println(getUserProfileRequest);
        try {
            ebay.apis.eblbasecomponents.GetUserProfileResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ebay.apis.eblbasecomponents.ShoppingInterface#findProducts(ebay.apis.eblbasecomponents.FindProductsRequestType  findProductsRequest )*
     */
    public ebay.apis.eblbasecomponents.FindProductsResponseType findProducts(FindProductsRequestType findProductsRequest) { 
        LOG.info("Executing operation findProducts");
        System.out.println(findProductsRequest);
        try {
            ebay.apis.eblbasecomponents.FindProductsResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
